baseURL = "https://alleetanner.github.io/graphical-data-apps/"
languageCode = "en-us"
defaultContentLanguage = "en"
languageName = "English"
title = "Graphical Data Apps"
theme = "LoveIt"

# default amount of posts in each pages
paginate = 50
# whether to use emoji code
enableEmoji = true
# whether to use git commit log
enableGitInfo = true


[author]
  name = "Alastair Tanner"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "courses"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "All courses"
    url = "https://alleetanner.github.io/code-teaching/"
    # title will be shown when you hover on this menu link
    title = "Courses"
  [[menu.main]]
    weight = 2
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Sections"
    url = "posts"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "about"
    title = ""
  [[menu.main]]
    weight = 6
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://github.com/alleetanner/graphical-data-apps"
    title = "GitHub"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
        
[params]
  # LoveIt theme version
  version = "0.2.X"
  title = ""
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = ""

  [params.header]
      desktopMode = "fixed"
      # mobile header mode ["fixed", "normal", "auto"]
      mobileMode = "auto"
  [params.header.title]
    # URL of the LOGO  
    logo = ""
    # title name
    name = "  Graphical Data Apps in Python"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<i class=\"fa-solid fa-cube\"></i> </i><i class=\"fa-brands fa-python\"></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
    typeit = false
  # Search config

[params.page.mapbox]
  # access token of Mapbox GL JS
  accessToken = "pk.eyJ1IjoiZmVyZ3VzY29vcGVyIiwiYSI6ImNrbXRudWpyMDB0cnkydnBtbWU5NXRrY28ifQ.0plSQ66uhgbhkhmeCnlqoQ"
  # style for the light theme
  lightStyle = "mapbox://styles/mapbox/light-v10"
  # style for the dark theme
  darkStyle = "mapbox://styles/mapbox/dark-v10"
  # whether to add NavigationControl
  navigation = true
  # whether to add GeolocateControl
  geolocate = true
  # whether to add ScaleControl
  scale = true
  # whether to add FullscreenControl
  fullscreen = true

[params.page.toc]
  # whether to enable the table of the contents
  enable = true
  # LoveIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
  keepStatic = true
  # whether to make the table of the contents in the sidebar automatically collapsed
  auto = false
